server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;


     location / {
       root   /usr/share/nginx/html;
       index  index.html index.htm;
     }

    location /api/users {
    	proxy_pass http://users-service:8083;
    }

    location /api/order {
    	
	auth_request /auth;

	auth_request_set $user_id                $upstream_http_x_user_id;
	auth_request_set $user_username          $upstream_http_x_user_username;
	auth_request_set $user_email             $upstream_http_x_user_email;
	auth_request_set $user_role              $upstream_http_x_user_role;
	
	add_header X-USER-ID $user_id;

	proxy_set_header X-USER-ID               $user_id;
	proxy_set_header X-USER-EMAIL            $user_email;
	proxy_set_header X-USER-USERNAME         $user_username;
	proxy_set_header X-USER-ROLE             $user_role;

	proxy_pass http://order-service:8082;
    }


    location = /auth {
	internal;
	
	proxy_pass_request_body off;
        proxy_set_header Content-Length "";	
	proxy_pass_request_headers on;    

	proxy_pass http://auth-service:8081/api/auth/verify;	
    
    }

}
